---

# Workaround for SNI support for python version 2.7.6 and earliers, see:
#     https://github.com/ansible/ansible/issues/9966
- name: Import mongodb-org gpg public signing key | python version <= 2.7.6
  shell: >
      wget -qO - "{{ mongodb_signing_key_url }}" | apt-key add - \
        && touch /tmp/{{ mongodb_signing_key_url.split('/')|last }}
  args:
    creates: /tmp/{{ mongodb_signing_key_url.split('/')|last }}
    warn:    false
  when: "{{ ansible_python_version | version_compare('2.7.6', '<=') }}" 

- name: Import mongodb-org gpg public signing key | python version > 2.7.6
  apt_key:
    url: "{{ mongodb_signing_key_url }}"
    state: present
  when: "{{ ansible_python_version | version_compare('2.7.6', '>') }}" 

- name: Add mongodb-org apt repository to sources.list
  apt_repository:
    repo:         "{{ mongodb_apt_repo }}"
    update_cache: yes
    state:        present

- name: Install mongodb
  apt:
    name:  "mongodb-org={{ mongodb_version|default('*') }}"
    state: present
    force: yes
  notify: Restart mongodb

- name: Ensure mongodb packages are up to date
  apt:
    name:  "{{ item }}={{ mongodb_version|default('*') }}"
    state: present
    force: yes
  with_items: 
    - mongodb-org-server
    - mongodb-org-mongos
    - mongodb-org-shell
    - mongodb-org-tools
  notify: Restart mongodb
